### PR TITLE
update rejective sampling and a simple tutorial on wiki

### PR DESCRIPTION
**Pull request by wangbingnan136**

### CODE REVIEW

**Comment by wangbingnan136** [comment]
https://github.com/wangbingnan136/CSRGraph

hello,I have updated the rejective sampling according to https://github.com/louisabraham/fastnode2vec,
can I merge to your great program?

**Comment by VHRanger** [comment]
Awesome! Yes, let me review it and integrate it. 

Should be done this week.

**Comment by wangbingnan136** [comment]
> Awesome! Yes, let me review it and integrate it.
> 
> Should be done this week.

Thanks~

**Comment by VHRanger** [comment]
This is really good code, the only two changes I'd add is:

1. Unit test the rejective sampling strategy
2. Benchmark it and possibly deploy it as the default random walk strategy if it's faster than the normal method in all cases? 

I'm not merging yet because I want to check these things out and merge all of it at once (a lot of people depend on the NodeVectors package which mainly depends on the CSRGraph code).

**Comment by wangbingnan136** [comment]
I see.I think we need to introduce more kinds of graph data for testing.

**Pull request merged**
