### PR TITLE
Update graph.py

### PR DESCRIPTION
**Pull request by MAQ-Ravijit-Ramana**
JitClass is not used also it has been moved to numba.experimental so can we remove this from code and update the package
https://github.com/numba/numba/issues/6539

### CODE REVIEW

**Comment by stuartarchibald** [comment]
> JitClass is deprecated so can we remove this from code and update the package
> [numba/numba#6539](https://github.com/numba/numba/issues/6539)

Just to clarify, `jitclass` itself is not deprecated. The original import location `numba.jitclass` is what was deprecated and has finally been removed in Numba 0.52. The new import location for `jitclass` is `numba.experimental.jitclass`.

**Comment by MAQ-Ravijit-Ramana** [comment]
yeah but it is not even used in the code. Thanks though i get what you are trying to say here.

**Comment by stuartarchibald** [comment]
> yeah but it is not even used in the code. Thanks though i get what you are trying to say here.

I guess no problem removing it then :) Just wanted to make sure that it is clear that `jitclass` itself is not deprecated, it's just moved.

**Comment by VHRanger** [comment]
Thanks

**Comment by MAQ-Ravijit-Ramana** [comment]
No worries mate.

**Comment by MAQ-Ravijit-Ramana** [comment]
Could you update and release the new version of csrgraph library ?

**Comment by VHRanger** [comment]
Should be on its way, 0.1.23 has your fix pushed upstream

**Pull request merged**
